### ISSUE TITLE
Errors on basic usage

### ISSUE THREAD

**Issue by theduke** [AgilionApps/ja_resource#28]
I'm getting this output from `mix phoenix.server` without any configuration:

```elixir
defmodule Dresspack.UserController do
  use Dresspack.Web, :controller
  use JaResource 
  plug JaResource
end
```

```
Compiling 14 files (.ex)
warning: undefined behaviour function repo/0 (for behaviour JaResource.Repo)
  web/controllers/user_controller.ex:2

warning: undefined behaviour function repo/0 (for behaviour JaResource.Repo)
  web/controllers/user_controller.ex:2

warning: undefined behaviour function repo/0 (for behaviour JaResource.Repo)
  web/controllers/user_controller.ex:2


== Compilation error on file web/controllers/user_controller.ex ==
** (CompileError) web/controllers/user_controller.ex:4: undefined function repo/0
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Any ideas?
(Phoenix 1.2.1)

**Comment by alanpeabody** [comment]
Sorry, been on vacation.

You need to either define repo/0 in your controller or set the config value. See these docs for more:

https://github.com/AgilionApps/ja_resource/blob/master/lib/ja_resource/repo.ex#L4

If that doesn't fix it let me know!

**Comment by alanpeabody** [comment]
@theduke going to close this for now, feel free to re-open if the above does not fix the issue.

**Comment by theduke** [comment]
Thanks.
Thanks.

Feeling really stupid here, but now I got the next issue:

```
 (UndefinedFunctionError) function Dresspack.RoleView.render/2 is undefined (module Dresspack.RoleView is not available)

**Comment by alanpeabody** [comment]
You do need a view, usually one implementing JaSerializer.
